### ISSUE TITLE
Typo in ElmBook.Chapter.withComponentList documentation

### ISSUE THREAD

**Issue by codewithcats** [dtwrks/elm-book#1]
A tiny issue but I don't know which is the right way to communicate so I go here. Please let me know if you think there is the better way to do 😅

Here in [ElmBook.Chapter.withComponentList](https://github.com/dtwrks/elm-book/blob/f41abcfcf0d2b40537705c6d3c484bd2b2726845/src/ElmBook/Chapter.elm#L156) documentation, it says `withComponents` on the place that should be `withComponentList` -- I guess?

**Comment by georgesboris** [comment]
@codewithcats thanks for the report – a small typo based on an older API! 😅 I believe it's fixed in the current release! 🙂
