### ISSUE TITLE
Add ability to have a custom Msg

### ISSUE THREAD

**Issue by NeoVier** [dtwrks/elm-book#12]
## Problem

Right now, it's not possible to have a `Cmd` that returns another kind of `Msg` other than the one in `ElmBook.Internal.Msg`. This is important because sometimes we might have children components which execute `Cmd`s and return their own `Msg` type. With the current API, it's not possible to have these kinds of components.

## Solution

We already have `initialState` and `subscriptions` on `StatefulOptions`. We could embrace The Elm Architecture even more and have an `update : (subMsg -> state -> ( state, Cmd subMsg )) -> Attribute state subMsg` function. This would then be used at the top level by the user, and the user could use a `Chapter.map : (subMsg -> mappedSubMsg) -> Chapter state subMsg -> Chapter state mappedSubMsg` function to have chapters with their own `update` function that returns their custom `Cmd`s.

**Comment by NeoVier** [comment]
@georgesboris if this is something you actually want in the package, and the solution sounds ok, I'd be happy to open a pull request with these changes, just let me know! :smile:

**Comment by georgesboris** [comment]
Hey! 👋  –

Thanks for the suggestion and feedback! This made me think about quite a few things that will hopefully simplify the next major version of elm-book. Your PR contained quite a few breaking changes in regards to API tho (even changing a simple type argument would cause the version bump to be a major one) so I worked on a solution that would not impact the current users that much based on some ideas of your!

The changes are now [released](https://github.com/dtwrks/elm-book/releases/tag/1.3.0) so I think its safe to close this issue! 😊  Let me know if you feel your needs are still not met! Thanks!

**Comment by NeoVier** [comment]
Looks great @georgesboris, thank you! It definitely feels like a much smaller complexity jump than using the `updateState*` helpers!
