### ISSUE TITLE
Handle Html in Chapter model

### ISSUE THREAD

**Issue by loicknuchel** [dtwrks/elm-book#16]
Hello,

I'm trying to create a stateful chapter with a model holding some Html.
The problem is with Elm we have to specify the message of Html but can't find how to align types well and I don't see anything on your doc about this use case: https://elm-book-in-elm-book.netlify.app/guides/stateful-chapters

Is it possible? If yes, what types should be used? Do you have an example?

My chapter if you want to have a look: https://github.com/azimuttapp/azimutt/pull/57/files#diff-c9ee7b79dd1b6e81e3ab9c660f623a0892c6df7c66e77be47b41cff3c93967d6R130
BTW I'm using ElmCSS ;)

**Comment by georgesboris** [comment]
OMG the size of that PR 😅 

So! By reading through some of your chapter examples I couldn't find exactly what you described. But in theory your custom model can hold anything as long as you provide the type – however, ElmBook can only handle `ElmBook.Msg` as the final message passed through your html. You can still map your own messages to ElmBook's though!

Like, this is fine as a data type:

```elm
-- Chapter

type alias SharedState s =
    { s | chapter : List (Html msg) }

-- Book

type alias BookState msg =
    { chapter : List (Html msg)
    }
  
main : Book (BookState msg)
main =
    ...
```

The problem would happen if your view had `Html SomeOtherMsg` – but then I don't see why wouldn't you be able to just use `Html.Styles.map` to change it to a valid ElmBook msg when using it on your chapter. Does this make any sense at all? Please reach me on Slack if you wanna discuss further – we can jump on a call and figure out how to make it work! :)

**Comment by georgesboris** [comment]
Closing for now – but please reach me here or on Discord/Slack for further discussion! 🙇
