### ISSUE TITLE
Add a route prefix option

### ISSUE THREAD

**Issue by stefan-wullems** [dtwrks/elm-book#18]
We would prefer not to set up a separate dev server for `elm-book`. Instead we would like to setup elm book such that it is available at the `/elm-book` route on the same localhost port as the app we're currently developing.

Right now, however `elm-book` assumes it always "lives" at `/`. So clicking on a chapter in the sidebar always navigates to `/chapter_group/chapter`. 

We would like to have an option that would allow us to add a prefix to this route, so that `elm-book` navigates to `/${prefix}/chapter_group/chapter`. In other words, we would like to be able to specify on which route `elm-book` will "live".

**Comment by georgesboris** [comment]
That is a good idea! I'll track this as a feature - I'll touch elm-book with a few updates in the coming days and this is something I could tackle while at it. Thanks!

**Comment by stefan-wullems** [comment]
Just an idea: Perhaps it would be nice if an elm book application accepts a flag to configure the prefix. This way the prefix could be configured in something like webpack, by -- for instance -- adding a JS env variable that can be passed along to the elm book application.

**Comment by georgesboris** [comment]
@stefan-wullems yep! I'm planning on enabling a standard elm application setup with flags/init/etc on v2.

But for now we will need to make do with a `ElmBook.ThemeOptions.routePrefix` – I think you can still set it through webpack by replacing a string during your compilation step (if you need that).

**Comment by georgesboris** [comment]
This is now fixed on https://github.com/dtwrks/elm-book/releases/tag/1.4.0 .
Thanks for opening the issue!
