### ISSUE TITLE
How to override ComponentOptions per-component?

### ISSUE THREAD

**Issue by avh4** [dtwrks/elm-book#23]
The [docs for `ElmBook.Chapter.withComponentOptions`](https://package.elm-lang.org/packages/dtwrks/elm-book/latest/ElmBook-Chapter#withComponentOptions) say:

> [component options] can also be overriden on the component level. Take a look at the ElmBook.Component module for more details.

But there is no such `ElmBook.Component` module.

Is there a way to set component options for a single component?  If not, I humbly request that feature (my real end-goal is to make a horizontal layout option for a list of components, which I'm trying to do by building a custom html and adding it as a single component, but then I want that one component to use `ComponentOptions.displayBlock` and leave other components to render normally as cards).

**Comment by avh4** [comment]
Update: this is low-priority for me, as I ended up liking the end result better if I keep my horizontal component list layout all inside a card anyway.

**Comment by georgesboris** [comment]
Hey! @avh4 this is kinda of a "hidden" feature because it lies inside the markdown renderer - you can see an example and the full list of possibilities here:

https://package.elm-lang.org/packages/dtwrks/elm-book/latest/ElmBook-ComponentOptions

**Comment by avh4** [comment]
Ah, so I'd just make a `<component>` HTML node with the desired options?

**Comment by georgesboris** [comment]
yup! in v2 I want to make things simpler and I already know how... but for v1 it was the way I found to make it flexible but keep the API as simple as possible.

**Comment by avh4** [comment]
Thanks, question answered!   (I wasn't sure if you wanted answered questions to be closed or to be left open.)

**Comment by georgesboris** [comment]
I'm closing it! Hopefully it can still be accessed through search if someone looks for it! 😁
