### ISSUE TITLE
ChapterBuilder type isn't exposed

### ISSUE THREAD

**Issue by avh4** [dtwrks/elm-book#24]
The `ChapterBuilder` type is used by public functions (like [`ElmBook.Chapter.withComponent`](https://package.elm-lang.org/packages/dtwrks/elm-book/latest/ElmBook-Chapter#withComponent)), but it's not exposed.

I have a helper function I use for some company-specific component example layouts, but I'm unable to add a type signature to those helper functions because I can't refer to `ChapterBuilder`.  Ideally the type (though not its internals) would be exposed.

**Comment by georgesboris** [comment]
Hey! Could you explain a little bit more about it?

I understand that exposing the opaque type would enable you to build a "partial" builder I'm just curious what would be the use case! 🙂

**Comment by avh4** [comment]
I made a function that's an alternative to `Chapter.withComponentList`, that instead makes a layout of the given examples like this (which matches how our designers organized some pages of their design styleguide):

```plain
+----------------+----------------+
| example html 1 | example html 2 |
+----------------+----------------+   . . .
| label 1        | label 2        |
+----------------+----------------+
```

so I want to make that function have this type signature:

```
withHorizontalComponentList :
    List ( String, html )
    -> ChapterBuilder state html
    -> ChapterBuilder state html
```

but currently can't because `ChapterBuilder` can't be referred to.

(Note: related to https://github.com/elm/compiler/issues/2219 where it's arguably a compiler bug that pages are allowed to expose functions that refer to types that aren't exposed.)

**Comment by georgesboris** [comment]
This is now fixed on https://github.com/dtwrks/elm-book/releases/tag/1.4.0 .
Thanks for reporting it!
