### ISSUE TITLE
chapterLinks with absolute url break when put in a named section group

### ISSUE THREAD

**Issue by avh4** [dtwrks/elm-book#25]
```elm
main =
    book "Example book"
        |> Book.withChapterGroups
            [ ( "Non-empty name"
              , [ Chapter.chapterLink { title = "title", url = "https://example.com/" }
                ]
            ]
```

The link in the rendered navbar will be invalid, as it will be concatenated with the group's URL `http://localhost/non-empty-namehttps://example.com/` instead of being recognized as an absolute URL.

(Note that things work fine if the group's name is the empty string `""`.)

**Comment by georgesboris** [comment]
Nice! Haven't heard this yet - will fix it asap :) thanks for the report!

**Comment by georgesboris** [comment]
This is now fixed on https://github.com/dtwrks/elm-book/releases/tag/1.4.0 .
Thanks for reporting it!
