### ISSUE TITLE
Clicking a search result cancels the search instead of navigating to the clicked page

### ISSUE THREAD

**Issue by avh4** [dtwrks/elm-book#28]
Happens in:
- MacOS, Firefox 95.0.2
- Linux, Firefox 96.0

Steps to reproduce:
- In the docs/demo https://elm-book-in-elm-book.netlify.app :
- Click in the search field
- Type "Mark"
- Click the "Markdown" chapter in the filtered chapter list

Expected result:
- I'm taken to the Markdown chapter page

Actual result:
- The search is cleared, and I'm still on the same page I was on.

**Comment by georgesboris** [comment]
This is definitely an uncaught regression (would benefit from elm-program-test...) - thanks for reporting it! will look into it.

**Comment by georgesboris** [comment]
Fixed on 1.4.2.
