### ISSUE TITLE
Expose darkMode to customBook as well as to themeOptions

### ISSUE THREAD

**Issue by gampleman** [dtwrks/elm-book#3]
Our design system has concepts of dark and light and it would be neat if we could also switch the style of the rendered components based on what the book does.

**Comment by georgesboris** [comment]
@gampleman nice! Thanks for the feedback.

Yeah – I'm thinking about that as well. I'm planning on rolling out a new major version over the next 1-2 weeks and both this and the hash based navigation are definitely good candidates for it. I'm gonna leave these two issues open as tasks for me.

**Comment by georgesboris** [comment]
Oh – actually, this is even more interesting than I initially thought. You mean like exposing the current theme as part of the state that each stateful component receives?

What I had in mind was just enabling people to further customize the global theme based on the dark mode but this is even more interesting.

**Comment by georgesboris** [comment]
I just released the 1.2.0 version with this feature. Take a look here:
https://elm-book-in-elm-book.netlify.app/design-system/dark-components

Thank you for the request and the help with the hash based navigation! 🙂
