### ISSUE TITLE
Off-by-one error in the actions log at the bottom of a page

### ISSUE THREAD

**Issue by Janiczek** [dtwrks/elm-book#35]
In the below screenshot, the action log shows 9 actions, but the panel at the very bottom shows `(10)`. In general the number it shows is one more than the number of actions emitted.

<img width="829" alt="Screenshot 2022-09-02 at 11 18 38" src="https://user-images.githubusercontent.com/149425/188189802-08c5f0d8-493d-4bb0-b1b8-edba479cf9fa.png">

Expected: show `(9)` there if 9 actions have been emitted, not `(10)`.

_PS: the modal itself might somehow tell the user which actions are most recent (at the top? or at the bottom?)_

**Comment by georgesboris** [comment]
Thanks for reporting it! I've just fixed this issue and it should be available on 1.4.2 -- on to the scrolling issue we go! 🕵️
