### ISSUE TITLE
nsfw links in example md

### ISSUE THREAD

**Issue by asteroidb612** [dtwrks/elm-book#4]
Should the links in these examples be safe for work? 

https://github.com/dtwrks/elm-book/blob/1c37faf08551b4fd35f37dbd0e12755e768cf7c8/src/ElmBook/UI/Docs/Markdown.elm#L18

**Comment by georgesboris** [comment]
@asteroidb612  Oh geez! Thanks for the input! haha I had absolutely no idea this was an actually working link!

**Comment by georgesboris** [comment]
This was fixed on the current version (1.1.0). Thanks for reporting it! 🤦‍♂️ 😅

**Comment by asteroidb612** [comment]
Haha that's what I thought happened, it looks like an easy-to-type example url! 👍
