### ISSUE TITLE
Allow for custom JS

### ISSUE THREAD

**Issue by janwirth** [dtwrks/elm-book#45]
Some UI components depend on JS. I can not render. them in elm-book unless I can include javascript.

**Comment by georgesboris** [comment]
Hey @janwirth ! elm-book is just an elm application so you can include whatever you want like you would in a normal elm application. You can create your own custom index.html and render your elm application normally.

If you need any help with that please reach me on Slack as georgesboris. 🙂

**Comment by janwirth** [comment]
I'll try to figure it out, I did not know I can have my own index.html when using the elm-book CLI.
