### ISSUE TITLE
A typo in a tag silently breaks the whole chapter

### ISSUE THREAD

**Issue by Janiczek** [dtwrks/elm-book#47]
```
<component with=label="Empty actions list" />
```

Note the `with=label` instead of `with-label`.

This _silently_ breaks a chapter: nothing gets shown, but there's no error on the page nor in the console.

I suppose _any_ indication that the Markdown parser has failed would improve this.

**Comment by georgesboris** [comment]
Good catch! I'll improve this on the upcoming release!

**Comment by georgesboris** [comment]
Error fixed on the recently published patch - 1.4.3 . Thanks for reporting it!
